name: 云编译

on: 
#  schedule:
#    - cron: 0 22 2 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 校验本地文件
      uses: actions/checkout@master

    - name: 安装编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -yqq update
        sudo -E apt-get -yqq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git git-core gperf haveged help2man intltool lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncurses5-dev libreadline-dev libssl-dev libtool libz-dev lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: 克隆源代码
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: 克隆增强功能源代码
      run: |
        git clone https://github.com/shidahuilang/luci-app-fileassistant openwrt/package/luci-app-fileassistant
        git clone -b lede https://github.com/pymumu/luci-app-smartdns.git openwrt/package/luci-app-smartdns
        
        
        
        git clone https://github.com/lisaac/luci-app-diskman openwrt/package/tmp/luci-app-diskman
        mv openwrt/package/tmp/luci-app-diskman/applications/luci-app-diskman openwrt/package
        
        git clone https://github.com/vernesong/OpenClash.git openwrt/package/tmp/luci-app-openclash
        mv openwrt/package/tmp/luci-app-openclash/luci-app-openclash openwrt/package
#        git clone -b 18.06 https://github.com/riverscn/luci-app-omcproxy openwrt/package/luci-app-omcproxy
#        git clone https://github.com/openwrt/luci openwrt/package/tmp
#        mv openwrt/package/tmp/applications/luci-app-nut openwrt/package

    - name: 升级 feeds
      run: |
        cd openwrt
        sed -i '$a\src-git helloworld https://github.com/fw876/helloworld' feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 增加固件编译日期
      run: |
        cd openwrt
        echo '增加固件编译日期'
        #sed -i 's/5.10/5.4/g' target/linux/x86/Makefile
        sed -i '/exit/d' package/lean/default-settings/files/zzz-default-settings
        date=$(date -d "+8 hour" +"%y.%-m.%-d")
        echo -e "sed -i \"s/\(DISTRIB_REVISION='.*\)'/\\\1 Built by toy ($date)'/\" /etc/openwrt_release\n\nexit 0" >> package/lean/default-settings/files/zzz-default-settings
    - name: 导入自定义配置
      run: |
        [ -e files ] && mv files openwrt/files
        cd openwrt
        rm -f ./.config*
        touch ./.config
        #
        # ========================固件定制部分========================
        # 
        # 
        # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
        # 
        # 以下为定制化固件选项和说明:
        #
        #
        # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
        # 
        #          =========================================
        #         |  # 取消编译VMware镜像:                   |
        #         |  cat >> .config <<EOF                   |
        #         |  # CONFIG_VMDK_IMAGES is not set        |
        #         |  EOF                                    |
        #          =========================================
        #
        # 
        # 以下是一些提前准备好的一些插件选项.
        # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
        # 如果不需要代码块里的某一项配置, 只需要删除相应行.
        #
        # 如果需要其他插件, 请按照示例自行添加.
        # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
        # 
        # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
        # 
        # 编译x64固件:
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_Generic=y
        EOF
        
        # 虚拟机:
        # CONFIG_PACKAGE_open-vm-tools=y
        cat >> .config <<EOF
        CONFIG_PACKAGE_qemu-ga=y
        EOF
       
        # 设置固件大小:
        cat >> .config <<EOF
        CONFIG_TARGET_KERNEL_PARTSIZE=256
        CONFIG_TARGET_ROOTFS_PARTSIZE=768
        EOF
        
        # 固件压缩:
        cat >> .config <<EOF
        CONFIG_TARGET_IMAGES_GZIP=y
        EOF
        # 编译UEFI固件:
        cat >> .config <<EOF
        CONFIG_GRUB_EFI_IMAGES=y
        EOF
        
        # 编译传统固件:
        # cat >> .config <<EOF
        # CONFIG_GRUB_IMAGES=y
        # EOF
        
        # IPv6支持:
        cat >> .config <<EOF
        CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
        CONFIG_PACKAGE_ipv6helper=y
        EOF
        
        # USB3.0支持:
        cat >> .config <<EOF
        CONFIG_PACKAGE_kmod-usb-ohci=y
        CONFIG_PACKAGE_kmod-usb-ohci-pci=y
        CONFIG_PACKAGE_kmod-usb2=y
        CONFIG_PACKAGE_kmod-usb2-pci=y
        CONFIG_PACKAGE_kmod-usb3=y
        EOF
        
        # 多文件系统支持:
        cat >> .config <<EOF
        CONFIG_PACKAGE_kmod-fs-nfs=y
        CONFIG_PACKAGE_kmod-fs-nfs-common=y
        CONFIG_PACKAGE_kmod-fs-nfs-v3=y
        CONFIG_PACKAGE_kmod-fs-nfs-v4=y
        CONFIG_PACKAGE_kmod-fs-ntfs=y
        CONFIG_PACKAGE_kmod-fs-squashfs=y
        EOF
        
        # LuCI插件选择:
        cat >> .config <<EOF
        CONFIG_PACKAGE_luci-app-adbyby-plus=y
        CONFIG_PACKAGE_luci-app-advanced-reboot=y
        CONFIG_PACKAGE_luci-app-ssr-plus=y
        CONFIG_PACKAGE_luci-app-fileassistant=y
        CONFIG_PACKAGE_luci-app-sqm=y
        CONFIG_PACKAGE_luci-app-ddns=y
        CONFIG_PACKAGE_luci-app-samba=y
        CONFIG_PACKAGE_luci-app-upnp=y
        CONFIG_PACKAGE_luci-app-v2ray-server=y
        CONFIG_PACKAGE_luci-app-pptp-server=y
        CONFIG_PACKAGE_luci-app-softethervpn=y
        CONFIG_PACKAGE_luci-app-vlmcsd=y
        EOF
        
        # LuCI主题:
        # cat >> .config <<EOF
        # CONFIG_PACKAGE_luci-theme-argon=y
        # CONFIG_PACKAGE_luci-theme-rosy=y
        # CONFIG_PACKAGE_luci-theme-atmaterial=y
        # EOF
        
        # 常用软件包:
        cat >> .config <<EOF
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_nano=y
        CONFIG_PACKAGE_screen=y
        CONFIG_PACKAGE_tree=y
        CONFIG_PACKAGE_vim-fuller=y
        CONFIG_PACKAGE_wget=y
        CONFIG_PACKAGE_iperf=y
        CONFIG_PACKAGE_iperf3=y
        CONFIG_PACKAGE_rsync=y
        CONFIG_PACKAGE_rsyncd=y
        CONFIG_PACKAGE_hdparm=y
        CONFIG_PACKAGE_smartd=y
        CONFIG_PACKAGE_smartmontools=y
        CONFIG_PACKAGE_smartmontools-drivedb=y
        CONFIG_PACKAGE_openssl-util=y
        EOF
        
        # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
        cat >> .config <<EOF
        # # CONFIG_TARGET_IMAGES_PAD is not set
        # # CONFIG_VMDK_IMAGES is not set
        # CONFIG_PACKAGE_coremark is not set
        # CONFIG_PACKAGE_luci-app-docker is not set
        # CONFIG_PACKAGE_luci-app-zerotier is not set
        # CONFIG_PACKAGE_luci-app-wifischedule is not set
        # CONFIG_PACKAGE_luci-app-vsftpd is not set
        # CONFIG_PACKAGE_luci-app-usb-printer is not set
        # CONFIG_PACKAGE_luci-app-transmission is not set
        # CONFIG_PACKAGE_luci-app-xlnetacc is not set
        # CONFIG_PACKAGE_luci-app-openvpn is not set
        # CONFIG_PACKAGE_luci-app-openvpn-server is not set
        # CONFIG_PACKAGE_luci-app-qbittorrent is not set
        # CONFIG_PACKAGE_luci-app-vlmcsd is not set
        # CONFIG_PACKAGE_luci-app-accesscontrol is not set
        # CONFIG_PACKAGE_luci-app-autoreboot is not set
        # CONFIG_PACKAGE_autosamba is not set
        # CONFIG_PACKAGE_luci-app-unblockmusic is not set
        # CONFIG_UnblockNeteaseMusic_Go is not set
        # CONFIG_UnblockNeteaseMusic_NodeJS is not set
        # CONFIG_PACKAGE_luci-app-ramfree is not set
        # CONFIG_PACKAGE_luci-app-flowoffload is not set
        # CONFIG_PACKAGE_luci-app-airplay2 is not set
        # CONFIG_PACKAGE_luci-app-amule is not set
        # CONFIG_PACKAGE_luci-app-music-remote-center is not set
        # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
        EOF
        sed -i 's/^[ \t]*//g' ./.config
        echo '修改网关地址'
        sed -i 's/192.168.1.1/92.168.9.1/g' package/base-files/files/bin/config_generate
        make defconfig
#    - name: SSH 连接
#      uses: tanst/debugger-action@master

    - name: 下载编译所需源码
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: 编译
      run: |
        cd openwrt
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
    - name: 打包文件
      run: |
        cd openwrt
        echo "CompileDate=$(date -d "+8 hour" +%Y%m%d-%H%M%S)"  >> $GITHUB_ENV
        rm -rf ./artifact/
        mkdir -p ./artifact/firmware
        mkdir -p ./artifact/package
        mkdir -p ./artifact/buildinfo
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
        cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
        mv -f ./.config ./artifact/buildinfo/
        cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
    - name: 上传固件信息
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_buildinfo_${{ env.CompileDate }}
        path: ./openwrt/artifact/buildinfo/

    - name: 上传 package
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_package_${{ env.CompileDate }}
        path: ./openwrt/artifact/package/

    - name: 上传固件
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_firmware_${{ env.CompileDate }}
        path: ./openwrt/artifact/firmware/
